services:
  - type: web
    name: donatello
    docker:
      image: docker.io/cesarausa/donatello-test:latest
      buildCommand: docker build -t docker.io/cesarausa/donatello-test:latest .
      startCommand: python manage.py runserver 0.0.0.0:$PORT