# services:
#   - type: web
#     name: donatello
#     repo: https://github.com/DEV-AusA/donatello-test
#     branch: main
#     buildCommand: pip install -r requirements.txt
#     startCommand: python manage.py runserver 0.0.0.0:8000